### ISSUE TITLE
Why do we have dagpb specific logic here?

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-fetcher#17]
https://github.com/ipfs/go-fetcher/blob/32904718f3f1430f8d769dce5fe7e4de34412f97/fetcher.go#L195-L200

This isn't extensible or maintainable.

**Comment by willscott** [comment]
thought is to move this up higher into ipfs

**Comment by Stebalien** [comment]
Ah, got it. That would make more sense (especially if we could have a centralized place to configure IPLD codecs, etc.). I just don't want to have to modify this library every/any time we decide to add a new IPLD codec, ADT, etc.

**Comment by willscott** [comment]
The codec setup was removed from this repo / isn't in the current version
