### ISSUE TITLE
Consider separation between 'core interface' and helper methods

### ISSUE THREAD

**Issue by willscott** [ipfs/go-fetcher#7]
It would be useful to specify a clear "core interface" to this library in case other implementations are desired, and separate that from the utility methods that can be used to to simplify for downstream clients.

In particular, it seems that the core interface we're presenting are
`BlockMatchingOfType` and `NodeMatchingOfType`, with the other methods being simplified helper cases derived from these. Is that right?

**Comment by acruikshank** [comment]
This is a good point. I'm a little concerned it will add some (very little) complexity to the calling of the library, and its unlikely it's interface will be re-implemented (functionality is more likely to be added through configuration, or the interface will be superseded by a new one).

I'll try a quick PR to see how it looks.
